"""add stock batch tracking (remaining_qty, purchase_item_id on sales)

Revision ID: 21d75ed53ff0
Revises: 4dc94017f12d
Create Date: 2026-07-26 14:27:05.838202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d75ed53ff0'
down_revision = '4dc94017f12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_qty', sa.Integer(), nullable=True))

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_sale_item_purchase_item_id', 'purchase_item', ['purchase_item_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_item_purchase_item_id', type_='foreignkey')
        batch_op.drop_column('purchase_item_id')

    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.drop_column('remaining_qty')

    # ### end Alembic commands ###
