"""Add brand_type to Brand

Revision ID: 2c3526470c9d
Revises: 4e869b447737
Create Date: 2026-09-27 21:14:11.954108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3526470c9d'
down_revision = '4e869b447737'
branch_labels = None
depends_on = None


def upgrade():
    # server_default exists only so the brands already in the table get a value
    # on upgrade; new rows take the model-level default instead. The owner sets
    # the real type per brand from the Brands page (NGK -> aftermarket), so
    # there is deliberately no data backfill here.
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_type', sa.String(length=20), server_default='oem', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('brand_type')

    # ### end Alembic commands ###
