"""add sale is_walkin flag

Revision ID: 31be15880943
Revises: 87d2dbcefcf5
Create Date: 2026-08-30 18:13:00.786401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31be15880943'
down_revision = '87d2dbcefcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='1': every pre-existing sale with no linked Customer was
    # always displayed as "Walk-in" (the None/Walk-in distinction didn't
    # exist yet), so backfilling them all to True keeps that display
    # unchanged with no separate backfill script needed.
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_walkin', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('is_walkin')

    # ### end Alembic commands ###
