"""add gst tracking to purchase items

Revision ID: 3bbb658b402c
Revises: 4f078c41f46a
Create Date: 2026-08-29 22:39:58.846058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbb658b402c'
down_revision = '4f078c41f46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_before_gst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.drop_column('gst_rate')
        batch_op.drop_column('price_before_gst')

    # ### end Alembic commands ###
