"""add mrp_at_purchase snapshot to purchase items

Revision ID: 4dc94017f12d
Revises: ee40044c3eef
Create Date: 2026-07-26 13:17:57.613320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc94017f12d'
down_revision = 'ee40044c3eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mrp_at_purchase', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.drop_column('mrp_at_purchase')

    # ### end Alembic commands ###
