"""Add shop bill_footer for printed bill terms

Revision ID: 4e869b447737
Revises: e60db62614ec
Create Date: 2026-09-20 21:20:39.651958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e869b447737'
down_revision = 'e60db62614ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_footer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_settings', schema=None) as batch_op:
        batch_op.drop_column('bill_footer')

    # ### end Alembic commands ###
