"""add sale returns

Revision ID: 4f078c41f46a
Revises: 4bde6c8ec124
Create Date: 2026-08-16 20:58:15.915680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f078c41f46a'
down_revision = '4bde6c8ec124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('applied_to_sale_id', sa.Integer(), nullable=True),
    sa.Column('return_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['applied_to_sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_no')
    )
    op.create_table('sale_return_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_item.id'], ),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_return_item')
    op.drop_table('sale_return')
    # ### end Alembic commands ###
