"""add product vehicle_name

Revision ID: 810639050f3c
Revises: 21d75ed53ff0
Create Date: 2026-08-01 18:13:32.417584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810639050f3c'
down_revision = '21d75ed53ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('vehicle_name')

    # ### end Alembic commands ###
