"""drop old product/supplier brand text columns, now brand_id

Revision ID: 8b33fc16c3c1
Revises: a23432dd0f73
Create Date: 2026-08-02 13:28:22.008778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b33fc16c3c1'
down_revision = 'a23432dd0f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
