"""replace customer/mechanic flat discount_pct with brand-wise discounts

Revision ID: 9fef87c3743b
Revises: ef6f1e363615
Create Date: 2026-08-01 21:48:55.982399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fef87c3743b'
down_revision = 'ef6f1e363615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_brand_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic_brand_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('discount_pct')

    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_column('discount_pct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_pct', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_pct', sa.FLOAT(), nullable=True))

    op.drop_table('mechanic_brand_discount')
    op.drop_table('customer_brand_discount')
    # ### end Alembic commands ###
