"""add brand master table, brand_id on product/supplier/brand-discounts

Revision ID: a23432dd0f73
Revises: 9fef87c3743b
Create Date: 2026-08-02 13:25:26.682924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23432dd0f73'
down_revision = '9fef87c3743b'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: hand-adjusted from the autogenerated version — product.brand and
    # supplier.brand are deliberately NOT dropped here. They still have real
    # data (existing brand text) that a one-off backfill script needs to read
    # to populate the new brand_id columns; a second migration drops them
    # once that backfill has run. customer_brand_discount/mechanic_brand_discount
    # had zero rows at the time of this migration, so their brand -> brand_id
    # swap is safe to do directly, no backfill needed.
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('customer_brand_discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_customer_brand_discount_brand_id', 'brand', ['brand_id'], ['id'])
        batch_op.drop_column('brand')

    with op.batch_alter_table('mechanic_brand_discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_mechanic_brand_discount_brand_id', 'brand', ['brand_id'], ['id'])
        batch_op.drop_column('brand')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_brand_id', 'brand', ['brand_id'], ['id'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_supplier_brand_id', 'brand', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('mechanic_brand_discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_mechanic_brand_discount_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('customer_brand_discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_customer_brand_discount_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    op.drop_table('brand')
    # ### end Alembic commands ###
