"""add mechanic discount_pct

Revision ID: cd1e8cb31bb0
Revises: 810639050f3c
Create Date: 2026-08-01 18:32:44.230444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1e8cb31bb0'
down_revision = '810639050f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_column('discount_pct')

    # ### end Alembic commands ###
