"""Make category-wise discounts brand-specific

Revision ID: cec36fe9b5c6
Revises: 89b8f11b1239
Create Date: 2026-09-04 22:53:35.853991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec36fe9b5c6'
down_revision = '89b8f11b1239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_category_discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_customer_category_discount_brand_id', 'brand', ['brand_id'], ['id'])

    with op.batch_alter_table('mechanic_category_discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_mechanic_category_discount_brand_id', 'brand', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic_category_discount', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mechanic_category_discount_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('customer_category_discount', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_category_discount_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###
