"""drop mechanic commission_pct

Revision ID: e43bd3199b8b
Revises: cd1e8cb31bb0
Create Date: 2026-08-01 19:49:41.813272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43bd3199b8b'
down_revision = 'cd1e8cb31bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_column('commission_pct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_pct', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
