"""supplier multi-brand (supplier_brand link table replaces supplier.brand_id)

Revision ID: e60db62614ec
Revises: cec36fe9b5c6
Create Date: 2026-09-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60db62614ec'
down_revision = 'cec36fe9b5c6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'supplier_brand',
        sa.Column('supplier_id', sa.Integer(), nullable=False),
        sa.Column('brand_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='fk_supplier_brand_supplier_id'),
        sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='fk_supplier_brand_brand_id'),
        sa.PrimaryKeyConstraint('supplier_id', 'brand_id'),
    )

    # Hand-written, not autogenerated: existing single brand_id values must be
    # carried into the new link table before the column disappears, or every
    # supplier's brand silently reverts to none.
    connection = op.get_bind()
    connection.execute(sa.text(
        "INSERT INTO supplier_brand (supplier_id, brand_id) "
        "SELECT id, brand_id FROM supplier WHERE brand_id IS NOT NULL"
    ))

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')


def downgrade():
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_supplier_brand_id', 'brand', ['brand_id'], ['id'])

    # Best-effort: a supplier with more than one brand at downgrade time can
    # only keep one, so pick an arbitrary (MIN) brand_id rather than raising.
    connection = op.get_bind()
    connection.execute(sa.text(
        "UPDATE supplier SET brand_id = ("
        "  SELECT MIN(brand_id) FROM supplier_brand WHERE supplier_brand.supplier_id = supplier.id"
        ")"
    ))

    op.drop_table('supplier_brand')
