"""dynamic selling price, customer discount, gst-inclusive mrp

Revision ID: ee40044c3eef
Revises: e1a01cc35aca
Create Date: 2026-07-26 10:39:43.711835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee40044c3eef'
down_revision = 'e1a01cc35aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('selling_discount_pct')
        batch_op.drop_column('mrp_discounted_price')

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_column('gst_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_rate', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mrp_discounted_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('selling_discount_pct', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('discount_pct')

    # ### end Alembic commands ###
