"""drop sale.amount_paid, now computed from payments

Revision ID: ef6f1e363615
Revises: 0ac74237fef1
Create Date: 2026-08-01 21:10:10.026830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6f1e363615'
down_revision = '0ac74237fef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
